openapi: 3.0.4
info:
  title: Historical Events
  description: Historical Events is a simple tool for getting historical events. It returns a list of historical events between 300BC and 2012
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/historicalevents:
    get:
      summary: Get Historical Events by Keyword
      description: Historical Events is a simple tool for getting historical events. It returns a list of historical events between 300BC and 2012
      operationId: historicalevents
      parameters:
      - name: text
        in: query
        schema:
          type: string
        required: true
        description: The keyword for which you want to get the historical events (e.g., moon landing)
        example: moon landing
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  count: 6
                  filteredOn:
                  - text
                  events:
                  - year: '1969'
                    month: '05'
                    day: '18'
                    date: 1969/05/18
                    event: " Apollo program: ''Apollo 10'' (Tom Stafford, Gene Cernan, John Young) is launched, on the full dress-rehearsal for the Moon landing."
                    range: May
                    granularity: year
                  - year: '1969'
                    month: '05'
                    day: '25'
                    date: 1969/05/25
                    event: "Apollo program: ''Apollo 10'' returns to Earth, after a successful 8-day test of all the components needed for the upcoming first manned Moon landing."
                    range: May
                    granularity: year
                  - year: '1969'
                    month: '07'
                    day: '20'
                    date: 1969/07/20
                    event: " Apollo program: The lunar module ''Eagle'' lands on the lunar surface. An estimated 500 million people worldwide watch in awe as Neil Armstrong takes his historic first steps on the Moon at 02:56 UTC, the largest television audience for a live broadcast at that time.cite web|title=Manned Space Chronology: Apollo_11|url=<a href=\"http://www.spaceline.org/flightchron/apollo11.html|publisher=spaceline.org|accessdate=2008-02-06|\">http://www.spaceline.org/flightchron/apollo11.html|publisher=spaceline.org|accessdate=2008-02-06|</a> archiveurl= <a href=\"http://web.archive.org/web/20080214213826/http://www.spaceline.org/flightchron/apollo11.html|\">http://web.archive.org/web/20080214213826/http://www.spaceline.org/flightchron/apollo11.html|</a> archivedate= 14 February 2008 !--DASHBot--| deadurl= no}}cite web|title= Apollo Anniversary: Moon Landing quotInspired Worldquot|url=<a href=\"http://news.nationalgeographic.com/news/2004/07/0714_040714_moonlanding.html|publisher=nationalgeographic.com|accessdate=2008-02-06|\">http://news.nationalgeographic.com/news/2004/07/0714_040714_moonlanding.html|publisher=nationalgeographic.com|accessdate=2008-02-06|</a> archiveurl= <a href=\"http://web.archive.org/web/20080209140059/http://news.nationalgeographic.com/news/2004/07/0714_040714_moonlanding.html|\">http://web.archive.org/web/20080209140059/http://news.nationalgeographic.com/news/2004/07/0714_040714_moonlanding.html|</a> archivedate= 9 February 2008 !--DASHBot--| deadurl= no}}"
                    range: July
                    granularity: year
                  - year: '1969'
                    month: '07'
                    day: '20'
                    date: 1969/07/20
                    event: The ''Apollo 11'' astronauts return from the first successful Moon landing, and are placed in biological isolation for several days, on the chance they may have brought back lunar germs. The airless lunar environment is later determined to preclude microscopic life.
                    range: July
                    granularity: year
                  - year: '1971'
                    month: '02'
                    day: '08'
                    date: 1971/02/08
                    event: "Apollo program: ''Apollo 14'' returns to Earth after the third manned Moon landing."
                    range: February
                    granularity: year
                  - year: '1973'
                    month: '01'
                    day: '07'
                    date: 1973/01/07
                    event: Elvis Presley's concert in Hawaii. The first worldwide telecast by an entertainer watched by more people than watched the Apollo moon landings.
                    range: January
                    granularity: year
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
